name: Docker Image CI
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build the docker image
      run: docker build . --file Dockerfile 
    - name: tag image
      run: docker tag back-invest:$(date +%s) ${{secrets.DOCKER_USERNAME}}/back-invest
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USERNAME}}/prueba
