name: Docker Image CI

on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login Docker HUB
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build the docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/back-invests
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USERNAME}}/back-invests
